name: Deploy Static Website

on:
  push:
    branches: [ main ]
permissions:
  id-token: write
  contents: read

jobs:

  deploy:
    runs-on: ubuntu-22.04
    
    steps:
    - uses: actions/checkout@v3

    - id: 'auth'
      name: 'Authenticate to Google Cloud'
      uses: 'google-github-actions/auth@v2'
      with:
        service_account: 'my-service-account@static-website-assignment-5.iam.gserviceaccount.com'
        workload_identity_provider: 'projects/25284225882/locations/global/workloadIdentityPools/github/providers/my-repo'

    - name: 'Upload to Cloud Storage'
      uses: 'google-github-actions/upload-cloud-storage@v1'
      with:
        path: '.'
        destination: 'static-website-project-bucket'
        parent: false
